
os: linux
language: python
python: "3.7"
dist: xenial

compiler:
  - gcc

before_install:
  - pip install conan
  - conan user

langague: cpp

before_script:
  - mkdir -p ./build/
  - cd ./build/
  - conan install ../ --build=missing
  - cmake ../

script:
  - cmake --build ./

after_script:
  - cp bin/R_type_video_game ../
