language: cpp

os: linux
language: python
python: "3.7"
dist: xenial

compiler:
  - gcc

before_install:
  - sudo pip install conan
  - conan user

before_script:
  - mkdir -p ./build/
  - cd ./build/
  - conan install ../ --build=missing
  - cmake ../

script:
  - cmake --build build

after_script:
  - cp build/R_type_video_game ./
