
os: linux
language: cpp
dist: bionic

compiler:
  - gcc

name: Style, docs, and pip
cache: false
before_install:
  - pyenv global $(pyenv whence 2to3)
  - PY_CMD=python3
  - $PY_CMD -m pip install --user --upgrade conan
  - conan user

before_script:
  - mkdir -p ./build/
  - cd ./build/
  - conan install ../ --build=missing
  - cmake ../

script:
  - cmake --build ./

after_script:
  - cp bin/R_type_video_game ../
  - cd ../
  #Starting test libmy_network
  - sudo apt-get -y install libboost1.69-dev
  - cp lib/uti/my_network/
  - mkdir -p ./build.
  - cd ./build/
  - cmake ../
  - cd ../../../../build
  - make test
