
os: linux
language: cpp
python: "3.7"
dist: xenial

compiler:
  - gcc

before_install:
  - PY_CMD=python3
  - $PY_CMD -m pip install --user --upgrade conan
  - conan user

before_script:
  - mkdir -p ./build/
  - cd ./build/
  - conan install ../ --build=missing
  - cmake ../

script:
  - cmake --build ./

after_script:
  - cp bin/R_type_video_game ../
