
os: linux
language: cpp
dist: bionic

compiler:
  - gcc

name: Style, docs, and pip
cache: false
before_install:
  - pyenv global $(pyenv whence 2to3)
  - PY_CMD=python3
  - $PY_CMD -m pip install --user --upgrade conan
  - conan user

before_script:
  - mkdir -p ./build/
  - cd ./build/
  - conan install ../ --build=missing -g virtualenv
  - ./activate.sh
  - cmake ../

script:
  - cmake --build ./

after_script:
  - cp bin/R_type_video_game ../
  - cd ../
  #Starting test libmy_network
  #- sudo add-apt-repository -y ppa:lyx-devel/release
  #- sudo apt-get update -qq
  #- sudo apt-get -y install libboost-dev
  - cd lib/uti/my_network/
  - mkdir -p ./build/
  - cd ./build/
  - cmake ../
  - make test
