
os: linux
language: cpp
dist: bionic

compiler:
  - gcc

name: Style, docs, and pip
cache: false
before_install:
  - pyenv global $(pyenv whence 2to3)
  - PY_CMD=python3
  - $PY_CMD -m pip install --user --upgrade conan
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - sudo apt-get install -y libsfml-dev

before_script:
  - mkdir -p ./build/
  - cd ./build/
  - conan install ../ --build=missing -g virtualenv
  - source activate.sh
  - cmake ../

script:
  - cmake --build ./

after_script:
  - cp bin/R_type_video_game ../
  - cd ../
  #run tests on network library
  - cd lib/uti/my_network/
  - mkdir -p ./build/
  - cd ./build/
  - cmake ../
  - make test
