language: cpp

os:
  - linux

compiler:
  - gcc

before_install:
  - pip install conan
  - conan user

before_script:
  - mkdir -p ./build/
  - cd ./build/
  - conan install ../ --build=missing
  - cmake ../

script:
  - cmake --build build

after_script:
  - cp build/R_type_video_game ./
